base/urls.py
from django.urls import path
from . import views

# use include;      model_detail;           app_name = 'public_exam;

urlpatterns = [
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('', views.questions, name='questions'),
    path('question-post/', views.questionPost, name='question-post'),
    path('exams/', views.exams, name='exams'),
    path('exam-apply/', views.examApply, name='exam-apply'),
    path('exam-post/', views.examPost, name='exam-post'),
    path('notifications/', views.notifications, name='notifications'),
    path('account-settings/', views.account_settings, name='account-settings'),
    path('support/', views.support, name='support'),
    path('info/', views.info, name='info'),
    path('report-post/', views.reportPost, name='report-post'),
    path('questions-user/', views.questionsUser, name='questions-user'),
    path('exams-user/', views.examsUser, name='exams-user'),
]

# customer settings
# login pages

pubq/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls'))
]

base/models.py
from django.db import models
from django.contrib.auth.models import User

# only for PostgreSQL
# from django.contrib.postgres.fields import ArrayField
# models.Manager


class State(models.Model):
    initials = models.CharField(max_length=2)

    def __str__(self):
        return self.initials

class City(models.Model):
    name = models.CharField(max_length=100)

    state = models.ForeignKey(State, on_delete=models.PROTECT)

    def __str__(self):
        return self.name


class Address(models.Model):
    neighborhood = models.CharField(max_length=200)
    number = models.CharField(max_length=20, blank=True, null=True)
    complement = models.CharField(max_length=200, blank=True, null=True)

    city = models.ForeignKey(City, on_delete=models.PROTECT)

    def __str__(self):
        return self.neighborhood


SEX = [
    ('M', 'Male'),
    ('F', 'Female'),
    ('O', 'Other'),
]

COLORS = [
    ('W', 'White'),
    ('B', 'Black'),
    ('G', 'Grey'),
]

class StandardUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    profile_pic = models.ImageField(default='profile1.png', blank=True, null=True)
    nickname = models.CharField(max_length=200, blank=True, null=True)
    firstname = models.CharField(max_length=100, blank=True, null=True)
    lastname = models.CharField(max_length=200, blank=True, null=True)
    birth = models.CharField(max_length=8, blank=True, null=True)
    phone = models.CharField(max_length=11, blank=True, null=True)
    sex = models.CharField(max_length=1, blank=True, null=True)
    education = models.CharField(max_length=100, blank=True, null=True)
    color = models.CharField(max_length=1, choices=COLORS, default='W', blank=True)

    addresses = models.ManyToManyField(Address, blank=True)
    notifications = models.ManyToManyField('Notification', blank=True)


class TeacherStudents(models.Model):
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    note = models.CharField(max_length=2000)
    

class Report(models.Model):
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    note = models.CharField(max_length=2000)

    standarduser = models.ForeignKey(StandardUser, blank=True, null=True, on_delete=models.PROTECT)


class University(models.Model):
    profile_pic = models.ImageField(default='profile1.png', null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    name = models.CharField(max_length=200)
    initials = models.CharField(max_length=10)

    addresses = models.ManyToManyField(Address, blank=True)
    reports = models.ManyToManyField(Report, blank=True)

    def __str__(self):
        return self.initials


class Subject(models.Model):
    name = models.CharField(max_length=100)
    discipline_name = models.CharField(max_length=100)

    reports = models.ManyToManyField(Report, blank=True)

    def __str__(self):
        return self.name


class Discipline(models.Model):
    name = models.CharField(max_length=100)

    subjects = models.ManyToManyField(Subject, blank=True)

    def __str__(self):
        return self.name



class Answear(models.Model):
    text = models.CharField(max_length=5000)
    is_public = models.BooleanField(default=True, blank=True)

    reports = models.ManyToManyField(Report, blank=True)

EDUCATIONS = [
    ('M', 'Master'),
    ('H', 'High School'),
    ('P', 'Phd'),
    ('D', 'Degree'),
    ('T', 'Technical'),
    ('F', 'Fundamental'),
]

YEARS = [
    ('21', '2021'),
    ('20', '2020'),
    ('19', '2019'),
    ('18', '2018'),
    ('17', '2017'),
    ('16', '2016'),
    ('15', '2015'),
    ('14', '2014'),
    ('13', '2013'),
    ('12', '2012'),
    ('11', '2011'),
    ('10', '2010'),
    ('9', '2009'),
    ('8', '2008'),
    ('7', '2007'),
    ('6', '2006'),
    ('5', '2005'),
    ('4', '2004'),
    ('3', '2003'),
    ('2', '2002'),
    ('1', '2001'),
    ('0', '2000'),
]


DIFFICULTS = [
    ('E', 'Very Easy'),
    ('e', 'Easy'),
    ('m', 'Middle Level'),
    ('h', 'Hard'),
    ('H', 'Very Hard'),
]

class Question(models.Model):
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    text = models.CharField(max_length=10000)
    teacher_name = models.CharField(max_length=200)
    education_Level = models.CharField(max_length=1, choices=EDUCATIONS)
    year = models.CharField(max_length=2, choices=YEARS)
    answear = models.CharField(max_length=5000, blank=True, null=True)
    is_public = models.BooleanField(default=True, blank=True)
    wrong_answears_count = models.IntegerField(default=0, blank=True)
    difficult = models.CharField(max_length=1, blank=True, default='E', choices=DIFFICULTS)
    pic_1 = models.ImageField(blank=True, null=True)
    pic_2 = models.ImageField(blank=True, null=True)

    books = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True, blank=True)
    university = models.ForeignKey('University', on_delete=models.SET_NULL, null=True, blank=True)
    subject = models.ForeignKey(Subject, on_delete=models.SET_NULL, null=True, blank=True)
    exams = models.ManyToManyField('Exam', blank=True)
    answears = models.ManyToManyField(Answear, blank=True)
    reports = models.ManyToManyField(Report, blank=True)


class Exam(models.Model):
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    teacher_name = models.CharField(max_length=200, blank=True, null=True)
    education_Level = models.CharField(max_length=1, choices=EDUCATIONS)
    university_name = models.CharField(max_length=200, blank=True, null=True)
    wrong_answears_count = models.IntegerField(default=0, blank=True)
    is_public = models.BooleanField(default=True, blank=True)
    pic_1 = models.ImageField(blank=True, null=True)
    pic_2 = models.ImageField(blank=True, null=True)
    pic_3 = models.ImageField(blank=True, null=True)
    pic_4 = models.ImageField(blank=True, null=True)
    pic_5 = models.ImageField(blank=True, null=True)

    subjects = models.ManyToManyField(Subject, blank=True)
    reports = models.ManyToManyField(Report, blank=True)

    def __str__(self):
        return self.title


class TimeToApplyExam(models.Model):
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    date_to_apply = models.DateTimeField(blank=True, null=True)
    date_to_finish = models.DateTimeField(blank=True, null=True)

    exam = models.ForeignKey(Exam, on_delete=models.CASCADE, blank=True)

    def __str__(self):
        return self.date_to_apply


class Book(models.Model):
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    is_public = models.BooleanField(default=True, blank=True)
    note = models.CharField(max_length=400, blank=True, null=True)

    subject = models.ManyToManyField(Subject, blank=True)
    reports = models.ManyToManyField(Report, blank=True)

    def __str__(self):
        return self.title


class Commentary(models.Model):
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    text = models.CharField(max_length=2000)
    is_public = models.BooleanField(default=True, blank=True)

    standarduser = models.ForeignKey(StandardUser, blank=True, null=True, on_delete=models.PROTECT)
    reports = models.ManyToManyField(Report, blank=True)

    class Meta:
        abstract = True


class CommentaryQuestion(Commentary):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)


class CommentaryBook(Commentary):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)


class CommentaryAnswear(Commentary):
    answear = models.ForeignKey(Answear, on_delete=models.CASCADE)


class CommentaryUniversity(Commentary):
    university = models.ForeignKey(University, on_delete=models.CASCADE)


PERMISSION = [
    ('S', 'Student'),
    ('T', 'Teacher'),
    ('P', 'Poster'),
    ('O', 'Owner'),
]

class UserPermission(models.Model):
    standarduser = models.ForeignKey(StandardUser, blank=True, null=True, on_delete=models.PROTECT)
    permission = models.CharField(max_length=1, choices=PERMISSION)

    class Meta:
        abstract = True


class UserPermissionQuestion(UserPermission):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)


class UserPermissionExam(UserPermission):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)


class UserPermissionBook(UserPermission):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)


class UserPermissionAnswear(UserPermission):
    answear = models.ForeignKey(Answear, on_delete=models.CASCADE)


class UserPermissionUniversity(UserPermission):
    university = models.ForeignKey(University, on_delete=models.CASCADE)

class UserPermissionTeacher(UserPermission):
    teacher_students = models.ForeignKey(TeacherStudents, on_delete=models.CASCADE)

class UserPermissionStudents(UserPermission):
    teacher_students = models.ForeignKey(TeacherStudents, on_delete=models.CASCADE)

class Notification(models.Model):
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    not_pic = models.ImageField(default='notification.png', blank=True)
    message = models.CharField(max_length=1000, blank=True, null=True)

    reports = models.ManyToManyField(Report, blank=True)
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, blank=True, null=True
    )
    book = models.ForeignKey(
        Book, on_delete=models.CASCADE, blank=True, null=True
    )
    answear = models.ForeignKey(
        Answear, on_delete=models.CASCADE, blank=True, null=True
    )
    university = models.ForeignKey(
        University, on_delete=models.CASCADE, blank=True, null=True
    )
    commentary_question = models.ForeignKey(

base/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


# from django.forms import inlineformset_factory
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group


from .decorators import unauthenticated_user, allowed_users, admin_only
from .forms import *
from .models import *
from .filters import *


# from django.views import generic
# ListView; DetailView; FormView; DeleteView; UpdateView...@unauthenticated_user


@unauthenticated_user
def registerPage(request):
    form = CreateUserForm()
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get("username")
            group = Group.objects.get(name="student")
            user.groups.add(group)
            StandardUser.objects.create(user=user)
            messages.success(request, "Account was created for " + username)

            return redirect("login")

    context = {"form": form}
    return render(request, "accounts/register.html", context)


@unauthenticated_user
def loginPage(request):

    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("questions")
        else:
            messages.info(request, "Username OR password is incorrect")

    context = {}
    return render(request, "base/login.html", context)


def logoutUser(request):
    logout(request)
    return redirect("login")


@login_required(login_url="login")
def questions(request):
    filter = QuestionFilter(
        request.GET, queryset=Question.objects.filter(is_public=True)
    )
    paginator = Paginator(filter.qs, 5)
    page = request.GET.get("page")
    try:
        questions = paginator.page(page)
    except PageNotAnInteger:
        questions = paginator.page(1)
    except EmptyPage:
        questions = paginator.page(paginator.num_pages)
    questions_num = len(questions)
    context = {
        "page": page,
        "questions": questions,
        "filter": filter,
        "questions_num": questions_num,
    }

    return render(request, "base/questions.html", context)


@login_required(login_url="login")
def questionPost(request):
    form = QuestionForm()
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    context = {
        "form": form,
    }
    return render(request, "base/question-post.html", context)


@login_required(login_url="login")
def questionsUser(request):
    questions = set()
    for (
        permission_question
    ) in request.user.standarduser.userpermissionquestion_set.all():
        if permission_question.permission == "P":
            if permission_question.question != None:
                questions.add(permission_question.question)
    context = {
        "questions": questions,
    }
    return render(request, "base/my_questions.html", context)


@login_required(login_url="login")
def exams(request):
    exams = Exam.objects.filter(is_public=True)
    paginator = Paginator(exams, 6)
    page = request.GET.get("page")
    try:
        exams = paginator.page(page)
    except PageNotAnInteger:
        exams = paginator.page(1)
    except EmptyPage:
        exams = paginator.page(paginator.num_pages)
    context = {
        "page": page,
        "exams": exams,
    }
    return render(request, "base/exams.html", context)


@login_required(login_url="login")
def examPost(request):
    form = ExamForm()
    if request.method == "POST":
        form = ExamForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    context = {
        "form": form,
    }
    return render(request, "base/postexam.html", context)


@login_required(login_url="login")
def examsUser(request):
    exams = set()
    for permission_exam in request.user.standarduser.userpermissionexam_set.all():
        if permission_exam.permission == "P":
            if permission_exam.exam != None:
                exams.add(permission_exam.exam)
    context = {
        "exams": exams,
    }
    return render(request, "base/myexams.html", context)


# I should require that only teachers apply exams
@login_required(login_url="login")
def examApply(request):
    form = TimeToApplyExamForm
    context = {
        "form": form,
    }
    return render(request, "base/postexam.html", context)


@admin_only
def reports(request):
    context = {}
    return render(request, "base/reports.html", context)


@login_required(login_url="login")
def reportPost(request):
    form = ReportForm()
    if request.method == "POST":
        form = ReportForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    context = {
        "form": form,
    }
    return render(request, "base/postreport.html", context)


@login_required(login_url="login")
def notifications(request):
    notifications = Notification.objects.all()
    paginator = Paginator(notifications, 10)
    page = request.GET.get("page")
    try:
        notifications = paginator.page(page)
    except PageNotAnInteger:
        notifications = paginator.page(1)
    except EmptyPage:
        notifications = paginator.page(paginator.num_pages)

    context = {
        "page": page,
        "notifications": notifications,
    }
    return render(request, "base/notifications.html", context)


@login_required(login_url="login")
def account_settings(request):
    return render(request, "base/account_settings.html")


def support(request):
    return render(request, "base/support.html")


def info(request):
    return render(request, "base/info.html")


# Um professor posta uma prova e ganha créditos
# créditos para baixar as provas de outros professores

base/templates/base/apply_exam.html
{%  extends 'base/main.html' %}

{% block content %} 
<div>
    <h1 style="margin-bottom:40px;">Exams</h1>>	
    
    <form method="POST" action="">
        {% csrf_token %}
        <div class="input-group mb-3">
            {{form.date_to_apply}}
        </div>
        <div class="input-group mb-2">
            {{form.date_to_finish}}
        </div>
</div>
{% endblock %}

base/templates/base/books.html
{%  extends 'base/main.html' %}
{% csrf_token %}
{% block content %} 
<div>
    <div class="container">
        <h1 style="color:#252c35; margin-bottom:40px;">Books</h1>
        <a href="postbook" type="submit">Post Book</a>
    </div>
    <hr>
    <div class="container">
        {% for book in books %}
            <h4>{{book.title}}</h4>
            {% if book.note != None %}
                <p>{{book.note}}</p>
            {% endif %}
            <p>{{book.date_created}}</p>
                <div style="display:None;">
                    {% for question in book.questions.all %}
                        {% include 'base/question_display.html' %}
                    {% endfor %}
                </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

base/templates/base/exam_apply.html
{%  extends 'base/main.html' %}

{% block content %} 
<div>
    <h1 style="margin-bottom:40px;">Exams</h1>>	
    
    <form method="POST" action="">
        {% csrf_token %}
        <div class="input-group mb-3">
            {{form.date_to_apply}}
        </div>
        <div class="input-group mb-2">
            {{form.date_to_finish}}
        </div>
</div>
{% endblock %}

base/templates/base/exam_display.html
{% load static %}
<style>
</style>
<div class="container">
    <div style="display:inline-block; margin:5px; margin-right:20px;">
        <b>Disciplines: 
        {% for subject in exam.subjects.all %}
            {{subject.discipline_name}}
        {% endfor %}    
        </b>
    </div>
    <div style="display:inline-block; margin:5px; margin-right:20px;">
        <b>Subjects: 
        {% for subject in exam.subjects.all %}
            {{subject.name}} 
        {% endfor %}
        </b>
    </div>
    {% if exam.university_name != None %}
        <div style="display:inline-block; margin:5px; margin-right:20px;">
            <b>University:{{exam.university_name}}</b>
        </div>
    {% endif %}
    <div style="display:inline-block; margin:5px; margin-right:20px;">
        <b>Teacher:{{exam.teacher_name}}</b>
    </div>
    {% csrf_token %}
    {% for question in exam.question_set.all %}
        {% include 'base/question_display.html' %}
    {% endfor %}

base/templates/base/exams.html
{%  extends 'base/main.html' %}

{% block content %} 
<div>
    <div class="container">
        <div style="display: inline-block;">
            <h1 style="color:#252c35; margin-right: 10px;">Exams</h1>
        </div>
        <div style="display: inline-block;">
            <a style="color: #e35760; font-size: 22px; text-align: center;"  href="" type="submit">Post Exam</a>
        </div>
        <div style="display: inline-block;">
            <button>Apply Exam</button>
        </div>
    </div>
    <hr>
    {% csrf_token %}
    {% for exam in exams %}
        {% include 'base/exam_display.html' %}
    {% endfor %}
</div>
{% endblock %}

base/templates/base/info.html
{%  extends 'base/main.html' %}

{% block content %} 
<div class="container">
    <h1>Info</h1>
</div>
{% endblock %}

base/templates/base/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>

							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>

								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}			
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'register' %}" class="ml-2">Sign Up</a>
					</div>	
					<div class="mt-4">
						{% comment %} <div class="d-flex justify-content-center links">
							Forgot password? <a href="{% url 'reset_password' %}" class="ml-2">Reset password</a>
						</div>
			 			{% endcomment %}
				</div>
			</div>
		</div>
	</div>
</body>
</html>

base/templates/base/myquestions.html
{%  extends 'base/main.html' %}
{% block content %} 
<div class="container">
    <h1>My Questions</h1>
    <br>
    <button><a href="{% url 'postquestion' %}" type="submit">Post Question</a></button>
        {% csrf_token %}
        {% for question in questions %}
            {% include 'base/question_display.html' %}
        {% endfor %}
</div>
{% endblock %}

base/templates/base/notifications.html
{%  extends 'base/main.html' %}

{% block content %} 
<div class="container">
    <h1 style="margin-bottom:40px; color:#252c35;">Notification</h1>
    {% csrf_token %}
    {% for notification in notifications %}
        {% if notification.not_pic != None %}
            <div style="width:40px; height: 40px; display: inline-block;">
            <img style="width: 100%; height: 100%; border-radius: 50%;" src="notification.not_pic.url">
            </div>
        {% endif %}
        {% if notification.question != None %}
            <div style="display: inline-block;">
                <b>Question {{notification.question.id}}</b>
            </div>
        {% endif %}
        {% if notification.book != None %}
            <div style="display: inline-block;">
                <b>Book {{notification.book.id}}</b>
            </div>
        {% endif %}
        {% if notification.answear != None %}
            <div style="display: inline-block;">
                <b>Answear {{notification.answear.id}}</b>
            </div>
        {% endif %}
        {% if notification.university != None %}
            <div style="display: inline-block;">
                <b>University {{notification.university.id}}</b>
            </div>
        {% endif %}
        {% if notification.commentary_question != None %}
            <div style="display: inline-block;">
                <b>Commentary_Question {{notification.commentary_question.id}}</b>
            </div>
        {% endif %}
        {% if notification.commentary_book != None %}
            <div style="display: inline-block;">
                <b>Commentary_Book {{notification.commentary_book.id}}</b>
            </div>
        {% endif %}
        {% if notification.commentary_answear != None %}
            <div style="display: inline-block;">
                <b>Commentary_Answear {{notification.commentary_answear.id}}</b>
            </div>
        {% endif %}
        {% if notification.commentary_university != None %}
            <div style="display: inline-block;">
                <b>Commentary_University {{notification.commentary_university}}</b>
            </div>
        {% endif %}
        <div>
            <p>{{notification.message}}</p>
        </div>
    {% endfor %}
</div>
{% endblock %}

base/templates/base/password_reset.html
<h3>Password reset</h3>

<p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>

<form method="post">

	{% csrf_token %}
	{{form}}
	<input type="Submit" name="Send email">
	
</form>

base/templates/base/password_reset_done.html
<h3>Password reset complete</h3>

<p>Your password has been set. You may go ahead and log in now.</p>

<a href="/">Log in</a>

base/templates/base/question_post.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}
<style>
    .hidden{
        display:None;
    }
</style>
<br>
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.management_form }}
            {% for field in form %}
                {{field}}
                <hr>
            {% endfor %}
            <div style="margin-bottom:20px;">
                <p>Add Pictures: Max = 2</p>
                <input type="submit" name="Submit">
            </div>
            <div style="margin-bottom:20px;">
                <p>Submit</p>
                <input type="submit" name="Submit">
            </div>
            <div style="margin-bottom:20px;">
                <p>Come to Questions again</p>
                <input type="submit" name="Submit">
            </div>
        </form>
        <script>
            var form_fields = document.getElementsByTagName('input')


            for (var field in form_fields){	
                form_fields[field].className += ' form-control'
                form_fields[2].placeholder='Teacher';
                form_fields[3].placeholder='University';
                form_fields[4].placeholder='Text';
                form_fields[5].className = 'hidden';
                form_fields[6].className = 'hidden';
                form_fields[7].placeholder='Answear';

                
                for (var field in form_fields){	
                    form_fields[field].className += ' form-control'
                }
            }
        </script>
    </div>
{% endblock %}

base/templates/base/questions_user.html
{%  extends 'base/main.html' %}
{% block content %} 
<div class="container">
    <h1>My Questions</h1>
    <br>
    <button><a href="{% url 'postquestion' %}" type="submit">Post Question</a></button>
        {% csrf_token %}
        {% for question in questions %}
            {% include 'base/question_display.html' %}
        {% endfor %}
</div>
{% endblock %}

base/templates/base/report_post.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}
<br>
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.management_form }}
            {% for field in form %}
                {{field}}
                <hr>
            {% endfor %}
            <input type="submit" name="Submit">
        </form>
        <script>
            var form_fields = document.getElementsByTagName('input')
            
            for (var field in form_fields){	
                form_fields[field].className += ' form-control'
                form_fields[2].placeholder='Note';
            }
        </script>
    </div>
{% endblock %}